# Generated by Django 5.1.6 on 2026-09-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Historial de chat', 'verbose_name_plural': 'Historiales de chat'},
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='bot_response',
            field=models.TextField(verbose_name='Respuesta del asistente'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user_input',
            field=models.TextField(verbose_name='Mensaje del usuario'),
        ),
    ]
