# Generated by Django 5.1.6 on 2026-09-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_chathistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Código SKU')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('categoria', models.CharField(choices=[('Tarjetas Gráficas', 'Tarjetas Gráficas (GPU)'), ('Procesadores', 'Procesadores (CPU)'), ('Placas Madre', 'Placas Madre (Motherboards)'), ('Memorias RAM', 'Memorias RAM'), ('Almacenamiento', 'Almacenamiento (SSD / NVMe / HDD)'), ('Fuentes de Poder', 'Fuentes de Poder (PSU)'), ('Refrigeración', 'Sistemas de Refrigeración'), ('Gabinetes', 'Gabinetes / Chasis'), ('Monitores', 'Monitores'), ('Periféricos', 'Periféricos y Accesorios')], max_length=100, verbose_name='Categoría')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio ($ USD)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible')),
                ('stock_minimo', models.PositiveIntegerField(default=5, verbose_name='Stock Mínimo de Alerta')),
                ('especificaciones', models.TextField(blank=True, verbose_name='Especificaciones Técnicas')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('destacado', models.BooleanField(default=False, verbose_name='Producto Destacado')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-precio'],
            },
        ),
    ]
