# Generated by Django 5.1.6 on 2026-09-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_actualizar_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_existente',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Existente'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código del Producto'),
        ),
    ]
