# Generated by Django 5.1.6 on 2026-09-23 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_producto_cantidad_existente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Estado del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Precio (Bs.)'),
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (+)'), ('SALIDA', 'Salida (-)'), ('AJUSTE', 'Ajuste de Inventario')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('stock_previo', models.PositiveIntegerField(verbose_name='Stock Previo')),
                ('stock_resultante', models.PositiveIntegerField(verbose_name='Stock Resultante')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo / Justificación')),
                ('usuario', models.CharField(default='Administrador', max_length=100, verbose_name='Responsable')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock (Kardex)',
                'verbose_name_plural': 'Movimientos de Stock (Kardex)',
                'ordering': ['-fecha'],
            },
        ),
    ]
